language: php
php:
  - hhvm-nightly

services:
  - redis-server

env:
  matrix:
    - TEST=1 HACK=0

matrix:
  include:
    - php: hhvm-nightly
      env: TEST=0 HACK=1

script:
  - "if [ \"$TEST\" = \"1\" ]; then hhvm -vEval.EnableHipHopSyntax=true tests/runner.php -c phpunit.travis.xml; fi"
  - "if [ \"$HACK\" = \"1\" ]; then hh_client; fi"
