language: php
php:
  - hhvm

before_script:
  - sudo add-apt-repository ppa:mapnik/boost
  - wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
  - echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
  - sudo apt-get update
  - sudo apt-get install hhvm-nightly

script: tests/runner.php -c phpunit.travis.xml
