#!/bin/bash

if [ $# -ne 2 ]; then
	cat <<USAGE
Usage: $0 name folder

Creates a new ALTER script of the given name in the given folder.

USAGE
exit 1;
fi

TIME=`date +%s`

FILENAME="$2/$1.ALTER.$TIME.sql"

echo "ALTER TABLE \"$1\"" > $FILENAME
echo -n $'\t' >> $FILENAME

echo "Created $FILENAME"
